[workspace]
members = [
    "mistralrs",
    "mistralrs-core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Fast and easy LLM serving."
homepage = "https://github.com/EricLBuehler/fastserv"
repository = "https://github.com/EricLBuehler/fastserv"
keywords = ["machine-learning"]
categories = ["science"]
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0.80", feature = "std" }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.4.0"}