[workspace]
members = [
    "mistralrs-server",
    "mistralrs-core",
    "mistralrs-lora",
    "mistralrs-pyo3",
    "mistralrs",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Fast and easy LLM serving."
homepage = "https://github.com/EricLBuehler/mistral.rs"
repository = "https://github.com/EricLBuehler/mistral.rs"
keywords = ["machine-learning"]
categories = ["science"]
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0.80", feature = "std" }
candle-core = { git = "https://github.com/EricLBuehler/candle.git", version = "0.4.0" }
candle-nn = { git = "https://github.com/EricLBuehler/candle.git", version = "0.4.0" }
serde = "1.0.197"
serde_json = "1.0.114"
indexmap = { version = "2.2.5", features = ["serde"] }
either = { version = "1.10.0", features = ["serde"] }