[workspace]
members = [
    "fastserv",
    "fastserv-core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Fast and easy LLM serving."
homepage = "https://github.com/EricLBuehler/fastserv"
repository = "https://github.com/EricLBuehler/fastserv"
keywords = ["machine-learning"]
categories = ["science"]
license = "MIT"