[package]
name = "mistralrs-core"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
candle-nn.workspace = true
serde.workspace = true
serde_json.workspace = true
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.4.0" }
dirs = "5.0.1"
hf-hub = "0.3.2"
thiserror = "1.0.57"
tokenizers = "0.15.2"
tqdm = "0.6.0"
tracing = "0.1.40"
candle-sampling = { git = "https://github.com/EricLBuehler/candle-sampling.git", version = "0.2.0" }
range-checked = { git = "https://github.com/EricLBuehler/range-checked.git", version = "0.1.0" }
chrono = "0.4.34"
mistralrs-lora = { version = "0.1.0", path = "../mistralrs-lora" }
half = "2.4.0"

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
