[package]
name = "mistralrs-server"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
serde.workspace = true
serde_json.workspace = true
axum = "0.7.4"
clap = { version = "4.5.1", features = ["derive"] }
mistralrs-core = { version = "0.1.0", path = "../mistralrs-core" }
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
dyn-fmt = "0.4.0"
indexmap.workspace = true